/**
 * Created by DmytroPinchuk on 17.09.2019.
 */

public with sharing class SubjectInfoService {

/*    public static List<String> getObjectLabels(String objectName) {
        Map<String, Schema.SObjectField> fieldMap = Schema.SObjectType.objectName.fields.getMap();
        List<String> objectLabels = new List<String>();
        for (SObjectField field : fieldMap.values()) {
            DescribeFieldResult dfr = field.getDescribe();
            String fieldName = dfr.getName();
            String fieldLabel = dfr.getLabel();
            objectLabels.add(fieldLabel);
        }
        return objectLabels;
    }*/
}